version: "3.9.21"

services:
  web:
    build: .
    ports:
      - "5050:5050"
    environment:
      - DATABASE_URL=mysql+pymysql://bakulaai:bakulaai@192.168.2.249/bakulaai
      - SECRET_KEY=e561527382e2bd259206eecc257c2d47
    depends_on:
      - db

volumes:
  db_data:
