version: "3.8"

services:
  web:
    build: .
    ports:
      - "5050:5050"
    environment:
      - DATABASE_URL=mysql+pymysql://bakulaai:bakulaai@192.168.2.249/bakulaai
      - SECRET_KEY=dein-geheimer-schlüssel
    depends_on:
      - db

volumes:
  db_data:
